/**
 * /api/admin/gallery/upload
 *
 * POST – uploads gallery media (staff only).
 *  - Images: optimized automatically with sharp (apply the EXIF orientation,
 *    fit within 2000x2000, convert to webp) and written under
 *    `public/uploads/gallery` with a random name.
 *  - Videos: transcoded with ffmpeg to browser-compatible H.264/AAC MP4 and
 *    validated by their magic-byte signature. Width and height cannot be
 *    computed on the server, so the client reads them from a `<video>` element
 *    and sends them separately in the `POST /api/admin/gallery` body.
 *
 * The client posts hundreds of files here in batches of six (see
 * `BulkUpload.tsx`), which is why the per-request file limit is small — the
 * effectively "unlimited" behaviour comes from the client-side queue.
 *
 * Security:
 *  - File names are never derived from user input (crypto.randomUUID()). The
 *    transcode output always carries a name the application generated.
 *  - `file.type` is only the first filter; the real format is confirmed with
 *    sharp `metadata()` for images and a magic-byte signature for videos.
 *  - `.rotate()` applies the EXIF orientation and strips the metadata, so no
 *    GPS/EXIF data leaks.
 */

import { NextResponse } from 'next/server';
import { randomUUID } from 'node:crypto';
import { mkdir, rename, stat, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import sharp from 'sharp';
import { apiRequireStaff } from '@/lib/admin-auth';
import { apiError, safeLog } from '@/lib/api-error';
import { GALLERY_UPLOAD_DIR } from '@/lib/gallery/storage';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Maximum files per request — the client already sends batches of six, and
// this keeps a consistent upper bound on the server too.
const MAX_FILE_COUNT = 6;

// Maximum size per file, which differs by type (video can be far larger;
// images are still held to something reasonable).
const MAX_IMAGE_BYTES = 25 * 1024 * 1024;
const MAX_VIDEO_BYTES = 200 * 1024 * 1024;

// First filter — the real check is the actual format via sharp metadata().
const ACCEPTED_IMAGE_MIME = new Set([
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/avif',
]);
// These are the names sharp metadata().format returns.
const ACCEPTED_IMAGE_FORMATS = new Set(['jpeg', 'png', 'webp', 'avif']);

// First filter — the real check is the magic-byte signature.
const ACCEPTED_VIDEO_MIME = new Set([
  'video/mp4',
  'video/webm',
  'video/quicktime',
]);

interface UploadedFile {
  /** The original file name, so the client can track progress and match rows. */
  name: string;
  url: string;
  type: 'image' | 'video';
  width?: number;
  height?: number;
  size: number;
}

interface LoadError {
  name: string;
  reason: string;
}

async function deleteQuietly(filePath: string): Promise<void> {
  try {
    await unlink(filePath);
  } catch {
    // The temp file may never have been created; do not mask the real error.
  }
}

function runFfmpeg(args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn('ffmpeg', args, { stdio: 'ignore' });
    proc.once('error', reject);
    proc.once('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`ffmpeg exited with code ${code ?? 'unknown'}.`));
    });
  });
}

/**
 * Transcode every uploaded video to H.264/AAC MP4 for browser compatibility.
 * File names are generated by the application, so no user input is ever passed
 * to ffmpeg as a command parameter.
 */
async function transcodeVideoForWeb(input: Buffer): Promise<{
  fileName: string;
  size: number;
}> {
  const id = randomUUID();
  const sourcePath = path.join(GALLERY_UPLOAD_DIR, `.${id}.kaynak.tmp`);
  const tempOutputPath = path.join(GALLERY_UPLOAD_DIR, `.${id}.mp4.tmp`);
  const outputPath = path.join(GALLERY_UPLOAD_DIR, `${id}.mp4`);

  await writeFile(sourcePath, input);
  try {
    await runFfmpeg([
      '-y',
      '-i',
      sourcePath,
      '-map',
      '0:v:0',
      '-map',
      '0:a?',
      '-c:v',
      'libx264',
      '-preset',
      'medium',
      '-crf',
      '23',
      '-pix_fmt',
      'yuv420p',
      '-c:a',
      'aac',
      '-b:a',
      '128k',
      '-movflags',
      '+faststart',
      tempOutputPath,
    ]);
    await rename(tempOutputPath, outputPath);
    const info = await stat(outputPath);
    return { fileName: `${id}.mp4`, size: info.size };
  } catch (err) {
    await Promise.all([deleteQuietly(tempOutputPath), deleteQuietly(outputPath)]);
    throw err;
  } finally {
    await deleteQuietly(sourcePath);
  }
}

/**
 * ISO-BMFF (mp4/mov) signature: bytes 4-7 must be the ASCII "ftyp".
 * See https://developer.apple.com/standards/qtff-2001.pdf (Sec. 2.2.4)
 */
function hasIsoBmffSignature(input: Buffer): boolean {
  if (input.length < 12) return false;
  return input.toString('ascii', 4, 8) === 'ftyp';
}

/**
 * WebM/Matroska (EBML) signature: the file starts with `0x1A 0x45 0xDF 0xA3`.
 */
function hasWebmSignature(input: Buffer): boolean {
  return (
    input.length >= 4 &&
    input[0] === 0x1a &&
    input[1] === 0x45 &&
    input[2] === 0xdf &&
    input[3] === 0xa3
  );
}

/** Checks that a video file's magic bytes match its declared MIME type. */
function hasValidVideoSignature(mime: string, input: Buffer): boolean {
  if (mime === 'video/webm') return hasWebmSignature(input);
  // mp4 and mov (quicktime) are both ISO-BMFF based.
  return hasIsoBmffSignature(input);
}

export async function POST(req: Request) {
  const auth = await apiRequireStaff(req);
  if (!auth.ok) {
    return apiError(auth.message, auth.status);
  }

  let form: FormData;
  try {
    form = await req.formData();
  } catch {
    return apiError('Invalid form data.', 400);
  }

  const files = form
    .getAll('dosyalar')
    .filter((v): v is File => v instanceof File);

  if (files.length === 0) {
    return apiError('No file to upload.', 400);
  }
  if (files.length > MAX_FILE_COUNT) {
    return apiError(
      `You can upload at most ${MAX_FILE_COUNT} files at once.`,
      400
    );
  }

  try {
    await mkdir(GALLERY_UPLOAD_DIR, { recursive: true });
  } catch (err) {
    safeLog('api/admin/gallery/upload:mkdir', err);
    return apiError('Could not create the upload directory.', 500, 'SERVER_ERROR');
  }

  const successful: UploadedFile[] = [];
  const errors: LoadError[] = [];

  for (const file of files) {
    const name = file.name || 'isimsiz';

    if (file.size <= 0) {
      errors.push({ name, reason: 'The file is empty.' });
      continue;
    }

    const isImage = ACCEPTED_IMAGE_MIME.has(file.type);
    const isVideo = ACCEPTED_VIDEO_MIME.has(file.type);

    if (!isImage && !isVideo) {
      errors.push({ name, reason: 'Unsupported file type.' });
      continue;
    }

    const sizeLimit = isVideo ? MAX_VIDEO_BYTES : MAX_IMAGE_BYTES;
    if (file.size > sizeLimit) {
      const limitText = isVideo ? '200 MB' : '25 MB';
      errors.push({ name, reason: `The file exceeds the ${limitText} limit.` });
      continue;
    }

    if (isVideo) {
      try {
        const input = Buffer.from(await file.arrayBuffer());

        if (!hasValidVideoSignature(file.type, input)) {
          errors.push({
            name,
            reason: 'The file contents are not a valid video.',
          });
          continue;
        }

        const converted = await transcodeVideoForWeb(input);

        successful.push({
          name,
          url: `/uploads/gallery/${converted.fileName}`,
          type: 'video',
          size: converted.size,
        });
      } catch (err) {
        safeLog('api/admin/gallery/upload', err, { name }, 'warn');
        errors.push({ name, reason: 'Could not process the video.' });
      }
      continue;
    }

    try {
      const input = Buffer.from(await file.arrayBuffer());

      const frame = sharp(input, { failOn: 'none' });
      const meta = await frame.metadata();
      if (!meta.format || !ACCEPTED_IMAGE_FORMATS.has(meta.format)) {
        errors.push({ name, reason: 'The file contents are not a valid image.' });
        continue;
      }

      const { data, info } = await frame
        .rotate() // Apply the EXIF orientation and strip the metadata (including GPS).
        .resize({
          width: 2000,
          height: 2000,
          fit: 'inside',
          withoutEnlargement: true,
        })
        .webp({ quality: 82 })
        .toBuffer({ resolveWithObject: true });

      const fileName = `${randomUUID()}.webp`;
      await writeFile(path.join(GALLERY_UPLOAD_DIR, fileName), data);

      successful.push({
        name,
        url: `/uploads/gallery/${fileName}`,
        type: 'image',
        width: info.width,
        height: info.height,
        size: info.size,
      });
    } catch (err) {
      safeLog('api/admin/gallery/upload', err, { name }, 'warn');
      errors.push({ name, reason: 'Could not process the image.' });
    }
  }

  if (successful.length === 0) {
    return NextResponse.json(
      { ok: false, error: 'No files could be uploaded.', errors },
      { status: 422 }
    );
  }

  return NextResponse.json({
    ok: true,
    files: successful,
    ...(errors.length > 0 ? { errors } : {}),
  });
}
